import { z } from "zod";

/**
 * RFC 9457 defines the "Problem Details" format for HTTP APIs.
 * @see https://www.rfc-editor.org/rfc/rfc9457.html
 */

/**
 * Zod schema for RFC 9457 Problem Details.
 * Validates the structure of problem detail objects according to the specification.
 */
export const ProblemDetailsSchema = z.object({
  /**
   * A URI reference that identifies the problem type.
   * When dereferenced, it should provide human-readable documentation.
   * Defaults to "about:blank" when not present.
   */
  type: z.string().default("about:blank"),

  /**
   * A short, human-readable summary of the problem type.
   * Should not change between occurrences of the same problem type.
   */
  title: z.string().optional(),

  /**
   * The HTTP status code generated by the origin server for this occurrence.
   */
  status: z.number().int().min(100).max(599).optional(),

  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail: z.string().optional(),

  /**
   * A URI reference that identifies the specific occurrence of the problem.
   * May be a relative URI or an absolute URI.
   */
  instance: z.string().optional(),
});

/**
 * Extended schema that allows additional properties for domain-specific extensions.
 */
export const ExtendedProblemDetailsSchema = ProblemDetailsSchema.passthrough();

/**
 * TypeScript type for RFC 9457 Problem Details.
 * Inferred from the Zod schema.
 */
export type ProblemDetails = z.infer<typeof ProblemDetailsSchema>;

/**
 * TypeScript type for extended Problem Details with additional properties.
 */
export type ExtendedProblemDetails = z.infer<typeof ExtendedProblemDetailsSchema> &
  Record<string, unknown>;

/**
 * Content type header value for Problem Details JSON.
 */
export const PROBLEM_DETAILS_CONTENT_TYPE = "application/problem+json";

/**
 * Validates a problem details object against the RFC 9457 schema.
 *
 * @param data - The object to validate
 * @returns Validation result with parsed data or error
 *
 * @example
 * ```ts
 * const result = validateProblemDetails({
 *   type: 'https://example.com/errors/not-found',
 *   title: 'Resource Not Found',
 *   status: 404,
 *   detail: 'The requested user was not found',
 *   instance: '/users/123'
 * });
 *
 * if (result.success) {
 *   console.log(result.data);
 * }
 * ```
 */
export function validateProblemDetails(
  data: unknown,
): z.SafeParseReturnType<unknown, ProblemDetails> {
  return ProblemDetailsSchema.safeParse(data);
}

/**
 * Validates an extended problem details object (allows additional properties).
 *
 * @param data - The object to validate
 * @returns Validation result with parsed data or error
 *
 * @example
 * ```ts
 * const result = validateExtendedProblemDetails({
 *   type: 'https://example.com/errors/validation',
 *   title: 'Validation Error',
 *   status: 400,
 *   errors: [{ field: 'email', message: 'Invalid format' }]
 * });
 * ```
 */
export function validateExtendedProblemDetails(
  data: unknown,
): z.SafeParseReturnType<unknown, ExtendedProblemDetails> {
  return ExtendedProblemDetailsSchema.safeParse(data);
}

/**
 * Creates a Problem Details object with proper defaults.
 *
 * @param details - Partial problem details to create
 * @returns Complete problem details object
 *
 * @example
 * ```ts
 * const problem = createProblemDetails({
 *   status: 404,
 *   title: 'Not Found',
 *   detail: 'User with id 123 was not found'
 * });
 * ```
 */
export function createProblemDetails(
  details: Partial<ProblemDetails> & Pick<ProblemDetails, "status">,
): ProblemDetails {
  if (details.status === undefined) {
    throw new Error("status is required");
  }
  return ProblemDetailsSchema.parse({
    type: "about:blank",
    ...details,
  });
}

/**
 * Creates an extended Problem Details object with additional properties.
 *
 * @param details - Problem details with additional properties
 * @returns Extended problem details object
 *
 * @example
 * ```ts
 * const problem = createExtendedProblemDetails({
 *   type: 'https://api.example.com/errors/validation',
 *   status: 400,
 *   title: 'Validation Failed',
 *   validationErrors: [
 *     { field: 'email', message: 'Must be a valid email' }
 *   ]
 * });
 * ```
 */
export function createExtendedProblemDetails<T extends Record<string, unknown>>(
  details: Partial<ProblemDetails> & Pick<ProblemDetails, "status"> & T,
): ExtendedProblemDetails & T {
  return ExtendedProblemDetailsSchema.parse({
    type: "about:blank",
    ...details,
  }) as ExtendedProblemDetails & T;
}

/**
 * Helper to create HTTP response headers for Problem Details.
 *
 * @param additionalHeaders - Additional headers to include
 * @returns Headers object with Content-Type set to application/problem+json
 *
 * @example
 * ```ts
 * const headers = createProblemDetailsHeaders();
 * // { 'Content-Type': 'application/problem+json' }
 *
 * const headersWithCors = createProblemDetailsHeaders({
 *   'Access-Control-Allow-Origin': '*'
 * });
 * ```
 */
export function createProblemDetailsHeaders(
  additionalHeaders: Record<string, string> = {},
): Record<string, string> {
  return {
    ...additionalHeaders,
    "Content-Type": PROBLEM_DETAILS_CONTENT_TYPE,
  };
}

/**
 * Type guard to check if an object is a valid Problem Details object.
 *
 * @param value - Value to check
 * @returns True if the value is a valid Problem Details object
 *
 * @example
 * ```ts
 * if (isProblemDetails(error)) {
 *   console.log(`Error status: ${error.status}`);
 * }
 * ```
 */
export function isProblemDetails(value: unknown): value is ProblemDetails {
  return validateProblemDetails(value).success;
}
